### ISSUE TITLE
Add specs

### ISSUE THREAD

**Issue by jimhester** [AtomLinter/linter-lintr#7]
Will need to

1. Install R
2. Install lintr

**Comment by Arcanemagus** [comment]
3. should be taken care of automatically

**Comment by Arcanemagus** [comment]
Just a note: The tests here just need to verify that it is properly handling messages from the linter provider, especially since `lintr` is already testing how it handles the code itself.

You can use [linter-php](https://github.com/AtomLinter/linter-php) as a basic example, others have far more detailed test suites such as [linter-eslint](https://github.com/AtomLinter/linter-eslint).
